### ISSUE TITLE
Cannot Redeploy

### ISSUE THREAD

**Issue by xuhang57** [cyverse/atmosphere#319]
@steve-gregory 
Not exactly sure that whether this bug is a local one or not. But I think it worths to mention. 

How to Reproduce:
1. After an instance turns into `active` (with a floating ip assigned), go ahead and click `redeploy` button to redeploy that instance.
2. monitor the instance status and it stays in `Networking` state

3. Celery/flower gives me this in the `add_floating_ip` task:

```
Traceback (most recent call last):
  File "/opt/env/atmo/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/env/atmo/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "service/tasks/driver.py", line 1365, in add_floating_ip
    countdown=countdown)
  File "/opt/env/atmo/local/lib/python2.7/site-packages/celery/app/task.py", line 696, in retry
    raise ret
Retry: Retry in 64s: Conflict()
```

**Comment by xuhang57** [comment]
I think I can safely close this issue. This was a problem if you are using the user_network_init and reclaim_ip = True together.
