### ISSUE TITLE
Problem: Cannot launch a new volume using OpenStackAuthBackbend

### ISSUE THREAD

**Issue by xuhang57** [cyverse/atmosphere#391]
This may be an issue by using the OpenStackAuthBackend. Will investigate this and hopefully I could send a PR to fix this soon.  @steve-gregory 

Error message:

```
Internal Server Error: /api/v1/provider/3bab1cd5-bd77-40b5-8adf-28d98ee66075/identity/0f4f0131-1aa9-4977-b1b9-1a6b7d996fd2/volume
Traceback (most recent call last):
  File "/opt/env/atmo/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/opt/env/atmo/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/opt/env/atmo/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/env/atmo/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/env/atmo/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/env/atmo/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/env/atmo/lib/python2.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/opt/env/atmo/lib/python2.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/env/atmo/lib/python2.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/dev/atmosphere/api/v1/views/volume.py", line 318, in post
    snapshot=snapshot, image=image)
  File "/opt/dev/atmosphere/service/volume.py", line 159, in create_esh_volume
    **conn_kwargs)
  File "/opt/env/atmo/lib/python2.7/site-packages/rtwo/driver.py", line 330, in create_volume
    return super(EshDriver, self).create_volume(*args, **kwargs)
  File "/opt/env/atmo/lib/python2.7/site-packages/rtwo/driver.py", line 197, in create_volume
    return self._connection.create_volume(*args, **kwargs)
  File "/opt/env/atmo/lib/python2.7/site-packages/rtwo/drivers/openstack_facade.py", line 63, in service_catalog_switch
    new_service = lc_conn.service_catalog.get_endpoint(
AttributeError: 'NoneType' object has no attribute 'get_endpoint'
```

**Comment by xuhang57** [comment]
Not sure how I can get a 
```
<rtwo.drivers.openstack_facade.OpenStack_Esh_Connection object at 0x7f0491b2ef90>
``` 
by using python REPL.

I can only get: 
```
driver = get_esh_driver(identity) 
driver: <rtwo.OSdriver>
```
 and it doesn't have `driver.connection`.
